### ISSUE TITLE
No way to close pop-up

### ISSUE THREAD

**Issue by TimUnderhay** [bergben/ng2-image-gallery#2] opened 2017-04-20 23:34 UTC
After much haranguing, I was able to get ng2-image-gallery working, however I've noticed that there's no close button on the image pop-up, and escape doesn't do anything.  How does one close the pop-up (please see attached)?

![pop-up](https://cloud.githubusercontent.com/assets/15734900/25256647/962bcd18-25ef-11e7-82ec-3f7bde7b8ba2.png)

**Comment by bergben** [comment] 2017-04-21 10:14
Normally there should be a button for that. I will look into it ASAP, probably in the next 2-3 days.

**Comment by bergben** [comment] 2017-04-28 15:15
@citizentim seems like all your icons are missing, did you include font-awesome? 
See https://github.com/bergben/ng2-image-gallery#import-the-styles

**Comment by bergben** [comment] 2017-05-19 22:02
I have created a plnkr for ng2-image-gallery: http://plnkr.co/edit/Qyg5m7XsiKCBpqa6I4ku?p=preview

Please provide a plnkr that reproduces your problem. Closing this until then.

**Closed as completed by bergben** 2017-05-19 22:02 UTC

**Comment by majid701** [comment] 2017-07-26 08:44
@bergben @citizentim 
Had the same problem. Everything worked except no icons showing up for closing and moving left or right. The problem was the font awesome missing. So i just imported that in my style.scss as:

`@import url('~https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css');`

That fixed the problem. now the icons are showing up and they work!
Maybe font awesome should be added as a dependency in the css file of the package? @bergben 

P.S it would be great if keyboard controls could be added for scrolling with arrow keys and closing the popup with esc key!
